### ISSUE TITLE
代码运行报错 找不到id

### ISSUE THREAD

**Issue by petterEat** [zhujiang521/PlayAndroid#1]
val bottomDialogLl = holder.getView<LinearLayout>(R.id.bottomDialogLl)
val bottomDialogIv = holder.getView<ImageView>(R.id.bottomDialogIv)
val bottomDialogTv = holder.getView<TextView>(R.id.bottomDialogTv)

com.zj.play.view.article BottomDialogAdapter

**Comment by zhujiang521** [comment]
重新拉下代码就好了，刚才更新了些东西，那个嘞忘记删除了
