### ISSUE TITLE
main 分支拉取后无法编译通过

### ISSUE THREAD

**Issue by leolive123** [zhujiang521/PlayAndroid#14]
报错信息
A problem occurred configuring root project 'PlayAndroid'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find dokka-core-1.4.32.jar (org.jetbrains.dokka:dokka-core:1.4.32).
     Searched in the following locations:
         https://maven.aliyun.com/repository/jcenter/org/jetbrains/dokka/dokka-core/1.4.32/dokka-core-1.4.32.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

查阅后发现org.jetbrains.dokka:dokka-core:1.4.32应为org.jetbrains.dokka:dokka-core:1.4.30，但是全局搜索后发现并无这个东西

**Comment by zhujiang521** [comment]
pull下代码，应该都是没问题的了
