### ISSUE TITLE
main分支编译失败

### ISSUE THREAD

**Issue by Lambert-A** [zhujiang521/PlayAndroid#17]
![image](https://user-images.githubusercontent.com/13530853/145717754-59377728-e26f-4f97-b3eb-6dc5a52b22e7.png)

**Comment by zylRookie** [comment]
我也是编译遇到同样的问题

**Comment by zhujiang521** [comment]
已修复，pull下代码就好了


发自我的iPhone

**Comment by Lambert-A** [comment]
> 已修复，pull下代码就好了 发自我的iPhone
> […](#)
> 在 2021年12月14日，11:14，zylRookie ***@***.***> 写道： ﻿ 我也是编译遇到同样的问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢🙏

**Comment by Lambert-A** [comment]
大佬，还是不行，main分支git pull没有拉取到新提交的代码
<img width="749" alt="截屏2021-12-14 16 15 59" src="https://user-images.githubusercontent.com/13530853/145959338-d1b3ea6e-4ad1-4691-bb86-b66ee8550eff.png">
<img width="1920" alt="截屏2021-12-14 16 14 50 (2)" src="https://user-images.githubusercontent.com/13530853/145959386-afec6857-35af-4445-a2e9-0e6d52ce18b8.png">

**Comment by Lambert-A** [comment]
是compose分支吗，我看刚更新了README

**Comment by zhujiang521** [comment]
都可以的，compose分支更新点

发自我的iPhone

**Comment by Lambert-A** [comment]
> 都可以的，compose分支更新点 发自我的iPhone
> […](#)
> 在 2021年12月14日，16:19，Lambert ***@***.***> 写道： ﻿ 是compose分支吗，我看刚更新了README — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

compose分支可以编译通过，main分支不行，报错如上图

**Comment by zhujiang521** [comment]
那就对了，main分支修改的代码没有push成功，晚上重新push下就好了

发自我的iPhone

**Comment by Lambert-A** [comment]
> 那就对了，main分支修改的代码没有push成功，晚上重新push下就好了 发自我的iPhone
> […](#)
> 在 2021年12月14日，16:32，Lambert ***@***.***> 写道： ﻿ 都可以的，compose分支更新点 发自我的iPhone … 在 2021年12月14日，16:19，Lambert @.***> 写道： ﻿ 是compose分支吗，我看刚更新了README — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. compose分支可以编译通过，main分支不行，报错如上图 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好滴，♥️

**Comment by zhujiang521** [comment]
main分支的修复已提交，可以pull最新代码进行编译
