### ISSUE TITLE
room报错，升级到最新的2.4.2也还是报错

### ISSUE THREAD

**Issue by jackyHuangH** [zhujiang521/PlayAndroid#23]
PlayAndroid/PlayAndroid/model/build/tmp/kapt3/stubs/debug/com/zj/model/room/dao/ProjectClassifyDao.java:18: 错误: Not sure how to convert a Cursor to this method's return type (java.lang.Object).
    public abstract java.lang.Object getAllProject(@org.jetbrains.annotations.NotNull()

**Comment by dyjAndroid** [comment]
我也报这个错

**Comment by checheng** [comment]
我也是报错误: Not sure how to convert a Cursor to this method's return type (java.lang.Object).咋回事- -

**Comment by zhujiang521** [comment]
实在不好意思，最近项目有点忙，现在修复这个问题了，可以pull下代码再运行
