### ISSUE TITLE
华为HUAWEI nova 6适配

### ISSUE THREAD

**Issue by uiuang** [zhujiang521/PlayAndroid#3]
状态栏适配有问题
![027a90767083bc08549b64c27c4101f](https://user-images.githubusercontent.com/20654238/96820789-478d0080-1459-11eb-8e7e-dd87e1e53258.jpg)

**Comment by zhujiang521** [comment]
状态栏目前是写死的 20 dp，可以修改下 layout_title 布局中的高度，也可以尝试动态获取。
我之后适配吧

**Comment by zhujiang521** [comment]
已修改此问题：fe7a4cf
