### ISSUE TITLE
compose分支问题反馈，底部导航栏异常

### ISSUE THREAD

**Issue by ff-frida** [zhujiang521/PlayAndroid#33]
环境：
pixel3，Android 12.
2022年10月12日14:42:27编译compose分支代码。

![Screenshot_20221012_144018](https://user-images.githubusercontent.com/18607031/195268984-19206ac8-12aa-4ab9-b20a-8ab7badaa1d6.png)

**Comment by zhujiang521** [comment]
最新版本已修复，下拉最新代码即可。
问题解决方式：Modifier.navigationBarsPadding()
