### ISSUE TITLE
屏幕适配方案

### ISSUE THREAD

**Issue by Joehaivo** [zhujiang521/PlayAndroid#4]
采用dpXXX的资源方式相对没有这么直观， 可以改用JessYanCoding/AndroidAutoSize

**Comment by zhujiang521** [comment]
嗯嗯，我了解下用哪个库，周末拉个分支搞下试试

**Comment by zhujiang521** [comment]
又想了下，如果要改动的话工作量挺大，因为基本所有布局我都使用的 dpXXX 的方式，改的话都得动，我再看看吧

**Comment by Joehaivo** [comment]
用Replace in path (Ctrl+shift+R)就能全局替换文本了， 很快的

**Comment by zhujiang521** [comment]
替换完成并使用了，但是感觉在 pad 上 效果不太好。
你可以切换到 screen_adaptation 分支进行查看
