### ISSUE TITLE
文章很不错

### ISSUE THREAD

**Issue by Qdafengzi** [zhujiang521/PlayAndroid#5]
文章非常不错，看了好多MVVM的项目，感觉没有几个能把MVVM和协程真正玩转的。提个问题：GlobalScope协程用这个易引发内存泄漏吧，今天看了鸿洋的公众号有一篇写协程的文章。

**Comment by zhujiang521** [comment]
之前新增了 lifecycleScope，修改了下 Activity 中使用协程的方式，我再看看修改下直接使用 GlobalScope 的方式吧。

**Comment by zhujiang521** [comment]
修改了下协程的请求方式，你可以查看最新的提交
