### ISSUE TITLE
JVM target 1.8 & Required View.OnClickListener

### ISSUE THREAD

**Issue by tenSunFree** [zhujiang521/PlayAndroid#6]
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
![11111](https://user-images.githubusercontent.com/23090085/99140670-b804f700-267e-11eb-82b6-1d75a40b2ed4.jpg)

添加jvmTarget = "1.8"
![22222](https://user-images.githubusercontent.com/23090085/99140699-0a461800-267f-11eb-83d6-553bc8a1e45a.jpg)

Type mismatch. Required: View.OnClickListener Found: () → Unit
![33333](https://user-images.githubusercontent.com/23090085/99140704-1d58e800-267f-11eb-9299-c0fe10871e7e.jpg)

用View.OnClickListener包裹方法
![44444](https://user-images.githubusercontent.com/23090085/99140798-e3d4ac80-267f-11eb-894a-8a1aafb73c56.jpg)

**Comment by zhujiang521** [comment]
最新版本已经修改，pull 下代码即可
