### ISSUE TITLE
不支持java 8

### ISSUE THREAD

**Issue by tianshaokai** [zhujiang521/PlayAndroid#7]
![image](https://user-images.githubusercontent.com/6706496/110228363-7b198480-7f3b-11eb-8ed3-13f92e93c440.png)

**Comment by tianshaokai** [comment]
部分页面 title 不居中

**Comment by zhujiang521** [comment]
升级吧，我也不太清楚本地环境有什么问题，看这个报错也看不出什么

**Comment by tianshaokai** [comment]
报错的我已经解决了，降低了插件的版本，现在就是某些页面 title 不居中，还有首页 展示数据 有点少，左右滚动 不能上下滑动

**Comment by zhujiang521** [comment]
你在 master 分支下吗？还是 main 分支，具体那些页面呢

**Comment by tianshaokai** [comment]
我是master分支，首页，还有我的tab 一些一面

**Comment by tianshaokai** [comment]
大佬 我看你在main 分支有改title的记录，可是那时compose版本，可以在master 分支也改一下吗

**Comment by zhujiang521** [comment]
你加我微信细说吧，我不太清楚你说的哪块标题不居中：17695500274
