### ISSUE TITLE
官方正式版Studio 4.1.2 有提示导入项目使用的版本过低

### ISSUE THREAD

**Issue by LukasCodeLab** [zhujiang521/PlayAndroid#8]
官方正式版Studio 4.1.2 有提示导入项目使用的版本过低
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer
作者是否描述 相关工具 版本

**Comment by zhujiang521** [comment]
需要使用AndroidSdio Beta 4.2版本或者Canary版本，正式版本目前不支持 Compose

**Comment by LukasCodeLab** [comment]
![捕获](https://user-images.githubusercontent.com/15062292/110438517-6d0d6480-80f1-11eb-884e-7df8e38b3458.PNG)
Beta 4.2 好像也不行，也是提示，作者使用的是Canary版本？？

**Comment by zhujiang521** [comment]
对，我使用的是 Canary 版本，我本地三个版本都有😂

**Comment by sparrow007** [comment]
Hello, I am start learning this project, would you please tell me what's the backend codes or you just use API and integrate in your app?

**Comment by 15335179243** [comment]
> Hello, I am start learning this project, would you please tell me what's the backend codes or you just use API and integrate in your app?

Hello Indians, our project is open source, the back end is also open source, if you like, you can go to the official website to check it, hope the world coexists peacefully, technology has no borders, love you.

**Comment by zhujiang521** [comment]
> 您好，我开始学习这个项目，请您告诉我什么是后端代码，或者您仅使用API​​并集成到您的应用程序中？

怎么说，这个后台代码是现有的，可以直接进行调用的

**Comment by wenwenwen888** [comment]
4.2正式版也编译出问题了
```
Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'
org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
org.gradle.api.InvalidUserDataException: Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'
	
```

**Comment by wenwenwen888** [comment]
> 4.2正式版也编译出问题了
> 
> ```
> Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> com.intellij.openapi.externalSystem.model.ExternalSystemException: Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'
> org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
> 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
> 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
> 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
> 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> org.gradle.api.InvalidUserDataException: Invalid injected android support version '202.7660.26.42.7322048', expected to be of the form 'w.x.y.z'
> 	
> ```

自己解决了

**Comment by prience03** [comment]
@wenwenwen888  请问怎么解决的，我也遇到这个问题了

**Comment by wenwenwen888** [comment]
@prience03 降低gradle版本
